### PR TITLE
Change button class name

### PR DESCRIPTION
**Pull request by ShadyDeth**

### CODE REVIEW

**Comment by WilliamHartman** [comment]
This change looks like it should fix the issue. I checked the class on the button when it popped up for me and it was also "VGQNd"

**Review by WilliamHartman — APPROVED** [review]
The new class name for the button is "VGQNd", this fix should allow the extension to find and click it again.

**Review by KillaBoi — APPROVED** [review]

**Comment by trmcnvn** [comment]
There has to be a better way to select this button over the generated class name.

**Comment by Glaived** [comment]
> There has to be a better way to select this button over the generated class name.

I agree, but maybe it would be interesting to integrate the PR as is until a more elegant solution is found?

**Pull request merged**
