### PR TITLE
Changed the way to find the bonus button

### PR DESCRIPTION
**Pull request by freedbrt**
Since the twitch constantly changes class names, I think the best way to find the bonus button is to just get the first button.

### CODE REVIEW

**Review by ShadyDeth — APPROVED** [review]
Tested on Chrome and Firefox and it works.

Good to merge @trmcnvn

**Comment by rhys-saldanha** [comment]
How can you guarantee that the first button on the page is the claim bonus button? What happens if Twitch shuffle the page and suddenly this extension is clicking the log-out button? I agree that having to continuously update the class isn't great, but it's better to be too specific than too broad.

Edit: I might have misunderstood at what level the button search happens, time to pull the code

Edit 2: Apologies for not reading the code first, the search for a button is very targeted, I'm a +1 for this

**Comment by freedbrt** [comment]
@rhys-saldanha This cannot be guaranteed. I agree with you, but i see no other way out. My opinion, if we choose to hardcode the class name, or the tag name, I think the second is better.

**Comment by trmcnvn** [comment]
I'll look into a solution this weekend if time permits.

**Pull request merged**
